### ISSUE TITLE
Problems with opening .json file

### ISSUE THREAD

**Issue by miranausnerffg** [w3c/wai-wcag-em-report-tool#123]
We encountered the error that there is data in the exported .json, but it is not or only partially displayed when the .json is opened in the report tool. The general information is displayed correctly, but not the specified test results. when we open the file (in Chrome) we get the following error message:

![image](https://github.com/w3c/wai-wcag-em-report-tool/assets/62592003/e97f155d-26c2-48dd-a882-8cc87faf1c11)

We were able to reproduce the error by just creating a random sample (no structured sample), then entering test results to it, then creating a structured sample and entering test results to it. and then remove the random sample with the trashcan in step three.

**Comment by iadawn** [comment]
Upon investigating the JSON that was sent it seems that there are incorrect 'subject' references in the Assertions. The JSON includes an array `selectSample` that includes each of the sample pages. These all have an id of the form `_:subject\n`. There is then an array, `auditSample` of Assertions that include the result, outcome, test and subject. The subject relates back to the data in the `selectSample` array.

It seems that the file shared has subject ids in the `auditSample` array that are not in the `selectSample` array. This causes the error which stops the complete file being loaded.

Tried to reproduce using just a random sample and was unable to. When I created a random sample and no structured sample pages the random samples have Assertion entries and there are Assertion entries for a 'subject_1' sample which doesn't appear in the `selectSample` array. For some reason this doesn't cause the error.

**Comment by miranausnerffg** [comment]
'subject_1' should normally be the result for the entire sample which is not connected to a specific sample and I believe because of this reason it does not appear in `selectSample`.

**Comment by maryprouty** [comment]
My team encountered the same error in our Google Chrome console: "Expected required options: subject, test, but only got type, date, mode, result, subject, test." The issue occurred because a web page was removed from the structured sample list in the tool. However, this did not delete the assertions in the audit sample (as @iadawn describes above), so we ran into the error when the saved JSON was uploaded to the report tool again later.

Steps to reproduce the issue in the WCAG-EM Report Tool:

1. Open the [report tool](https://www.w3.org/WAI/eval/report-tool) in Google Chrome.
2. Select Start New Report.
3. In Step 3, add two web pages to the Structured Sample.
4. In Step 4, under Add results for your pages, select both of the web pages from your Structured Sample.
5. Go back to Step 3 and delete **one** of the web pages from the Structured Sample Web Pages list.
6. Select View Report. 
7. Select Download Report (JSON).
8. *Imagine you're coming back later to finish working on your report*
9. Select Open Report from the Overview page and open the JSON file that you previously saved.
10. Notice the error logged in the console.

Any help in fixing this issue would be greatly appreciated so that it's possible to delete web pages from the structured sample list without messing up the data in the JSON!

**Comment by miranausnerffg** [comment]
@maryprouty, the error seems to be related to #124. An idea for a possible solution has been described there.

**Comment by iadawn** [comment]
I have just tested this and the console error is no longer there. Also, it looks like notes from other samples in the audit are not being lost.

Plan is to release this when we do the WCAG 2.2 patch release... imminently

**Comment by iadawn** [comment]
Done
