### ISSUE TITLE
Translations - Ack and disclaimer for unofficial translations

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-wcag-em-report-tool#138]
Considering the new French ([ready to publish](https://github.com/w3c/wai-wcag-em-report-tool/pull/127)) and German ([ready to review](https://github.com/w3c/wai-wcag-em-report-tool/pull/82)) translations, we will soon have 3 translations of the WCAG-EM Report Tool!

Context about the translation seems therefore more important. In particular:
- [x] acknowledge volunteer contributions
- [ ] inform readers that the translation might not accurately reflect the intentions of the English original.
- [ ] in some situations, inform that the WCAG guidelines/SCs wording used in the WCAG-EM Report Tool is not based on an Authorized Translation. That would be the case for the German translation: no Authorized translation has been published yet, but I think preferable to allow volunteers to translate WCAG-EM Report Tool.

Example in WAI website: https://www.w3.org/WAI/design-develop/fr

@iadawn @mhansma96 Any thoughts on how to do it? How big of an effort to implement?

cc @shawna-slh

**Comment by mhansma96** [comment]
I believe in order to add a language, you should add it to the array of available languages and then add a folder with translations for that language, mapping the shortcode (en = english) of the language and the naming (for example ui.fieldname) in those files. It can be easiest to take another existing language as an example and then adding the translations. 

I shouldn't be that hard to implement, but I might miss some additional info or tasks related to credits/testing that the others might know better

**Comment by rvantonisse** [comment]
Hey, a quick tldr answer: default locale is first locale entered at src/locales/index.json

The file / locales are passed through to i18n initializing script src/scripts/i18n.js and there the first locale is picked as default.

**Comment by KodGit** [comment]
Dear @remibetin, @mhansma96,
Even if the french translation of the reporting tool is the first target of the State of Geneva (for french web accessibility experts), the german translation is another opportunity to promote the WCAG EM reporting tool in Switzerland and surrounding areas (for german web accessibility experts).
I strongly support this proposal and hope that the french translation "ready to publish" will be available online very soon.
