### ISSUE TITLE
Question about reports that are in progress

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-wcag-em-report-tool#49]
If someone has started a report in the old tool and needs to finish it,

1. will they be able to open the report in the new tool to finish it?  and if not...
2. will the URL change of the old tool affect them being able to import their report and continue/finish it?

Would hate for someone to lose a report in progress during this transition.  Want to know if someone will be able to continue their work in progress.    Thanks!

**Comment by hidde** [comment]
Hi Kris-Anne, thanks for checking! 

1. Yes, an export from the old tool can be imported in the new tool, it was tested for that to work. 
2. The old tool will stay online for a while on a preview tool so that folks can continue to use it should they want to. It will also still be on GitHub so worst case they can install it locally (we know some organisations have their own version of the tool installed; this does require some knowledge of the technology).

**Comment by shawna-slh** [comment]
@Hidde Thanks for quick reply. _(Below is not urgent -- can be next week.)_

Would you test this, too:
> will the URL change of the old tool affect them being able to import their report and continue/finish it?

Use Case:
* In the existing tool, Jan is working on a report. Jan saves it.
* The new tool is published and the old tool is available. (as a netlify preview?) Jan needs to finish this report and not be distracted by new UI.

Can Jan, a non-technical user, go to the old tool and import the existing report and work away at it?

**Comment by hidde** [comment]
> Can Jan, a non-technical user, go to the old tool and import the existing report and work away at it?

Thanks for double checking… so, yes, Jan could. The change of URL will not change the workings of the tool.
