### ISSUE TITLE
update "changelog" for users and messaging

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-em-report-tool#50]
Background: Here is a little about [purpose of changelogs](https://wai-website-theme.netlify.app/writing/#changelogs) -- although that's mostly for translations whereas this changelog is about informing regular users of the tool.

https://github.com/w3c/wai-wcag-em-report-tool/wiki/Changelog:-What's-new-in-the-2021-redesign-of-the-WCAG-EM-Report-Tool

I think the audience for that was mostly EOWG reviewers. Now we are using it for users.

Consider if edits would make it better meet the needs of users?

(Also if you can write it to apply now and also when we deploy, e.g., change
"...the differences between what's currently live and what is in the new 2021 version."
-> "...the differences between Version 2 and Version 3."

Also I'd like a few bullets &/or sentences summary for the announcements. Here's a reminder that Hidde is planning to add that to the top of the changelog to benefit users, and Shawn will pull from that for messaging.

p.s. ftr. I would slightly prefer the changelog be like the [others, in a WAI page](https://www.w3.org/WAI/standards-guidelines/changelog/).  Although it probably doesn't matter (and maybe we should start changing to using GitHub wiki pages instead)?

**Comment by hidde** [comment]
Note that the '[What's new](https://github.com/w3c/wai-wcag-em-report-tool/wiki/Changelog:-What's-new-in-the-2021-redesign-of-the-WCAG-EM-Report-Tool)' previously didn't have the word Changelog in it, as it is, as you say, more directed at EO reviewers and not so much the general public.

I'll add a CHANGELOG.md to the project. We had a [CHANGELOG.md in the 2.0.0 version](https://github.com/w3c/wcag-em-report-tool/blob/master/changelog.md), but it wasn't updated consistently. Because 3.0.0 is a complete rebuild, I propose we start updating it from there.

So as soon as 3.0.0 is live, we start adding changes to this log.

**Comment by hidde** [comment]
Have added a list of changes to the wiki, for use in announcements etc:

<img width="933" alt="The most obvious changes in version 3 are: list, 4 items, item 1, simplified UI, also follows current WAI website design conventions; item 2: added Markdown support for observations, so that you can add code examples, images, links and more; item 3: improved performance; item 4: added progress bars per principle to see project completion at a glance" src="https://user-images.githubusercontent.com/178782/129025808-a5114e73-816a-48e0-a532-b1ba866b1752.png">

**Comment by hidde** [comment]
Closing this as we now have the changes in the changelog wiki page and there is a [changelog](https://github.com/w3c/wai-wcag-em-report-tool/blob/main/CHANGELOG.md) in the repository following [keep a changelog conventions](https://keepachangelog.com/en/1.0.0/).
