### ISSUE TITLE
Step 2 - adding technologies slightly confusing

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-wcag-em-report-tool#8]
The combination of the button label "Add other Web Technology" and the spacings/separation between the fields "Web Technology", "Specification Address", and the button make it unclear. In particular, for most other fields it is sufficient to simply add the text that will appear in the report. But for these fields you have to press the add *other* technology button to get your current text into the report. We should probably consider making the "show info" text more explanatory too.

**Comment by hidde** [comment]
Michel and Hidde discussed, we'll: 

- add gray background like in 'Add web page'
- add padding like in 'Add web page'

This should make it a lot clearer that they belong together and probably solves this issue at a minimum.

We'll also look at this, for bonus points: 

- maybe only show the fields after pressing a button (that's how it works in Add web page, but may be a bit weird here)
- maybe display next to each other (seems sensible because technology name probably always short)

**Comment by hidde** [comment]
Hidde and @nitedog  discussed: @mhansma96 please also:

- remove 'Note' and the sentence behind it from the Show Info under 'Web Technologies Relied on'
- add heading inside the add web page box
- we may not need a show info in this box anymore, because that is now obvious with the new affordances

**Comment by hidde** [comment]
Hey @nitedog, a new version of this is now live on https://wcag-em-report-tool-2021-redesign.netlify.app/. 

@mhansma96 has: 

- added box around 'add technology' field, with a header and background and the fields displaying next to each other if there is space
- removed the note about how to add a new technology
- removed the show info, as it is now clear what will happen and what is required

Let us know if you're happy with this, or have ideas to improve?

**Comment by nitedog** [comment]
Yes, looks good to me! Just minor CSS bug when you tab into "Web Technologies Relied Upon" the bluish background starts in the middle of the line of text.

**Comment by hidde** [comment]
Agreed this background is a bit odd, though it is part of the [Forms components in the WAI Design Components](https://wai-website-theme.netlify.app/components/form/elements/), see the radio buttons example. 

The `legend` 'sticks' out of the `fieldset`, that's a standard thing in browsers. We could consider using a heading and ARIA instead, because this default styling is hard to override. See also this [post from 2007 (!)](https://www.456bereastreet.com/lab/styling-form-controls-revisited/legend/#list) .
