### ISSUE TITLE
The ability to assign multiple success criteria

### ISSUE THREAD

**Issue by sophieschoice** [w3c/wai-wcag-em-report-tool#88]
As an auditor I sometimes assign multiple success criteria to an issue that I have found, but this is not quite supported in the tool. You can do it, though, by copying and pasting the text by the other success criteria, but it is easy to loose track with that approach.

Perhaps it is an idea to have the adding issues process a bit different? That, just like with Github issues or Jira, you have a field to enter the title, a text area to document the issue and that you can select the success criteria it applies to?

**Comment by hidde** [comment]
Thanks for this idea and providing a use case! I can see how that would be helpful.

However… this tool is fundamentally Success Criteria-based, not Issue-based. This would basically require us to flip the UI around. Because of that, this would be too much of a change, both in terms of UI and in terms of code and data structure.

(Partially related: we did explore moving towards more of an issue-based approach in https://github.com/w3c/wcag-em-report-tool/issues/371, but ended up not implementing for now. )
